memeja/urls.py
from django.conf.urls import patterns, include, url

#from webapp.views import index
from django.views.static import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

#from ajax_select import urls as ajax_select_urls

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'webapp.views.home', name='home'),
    # url(r'^memeja/', include('memeja.foo.urls')),

    # First page that user comes to 
    url(r'^$', include('webapp.urls')),
    url(r'', include('social_auth.urls')),

    # invitation urls
    url(r'^', include('invitation.urls')),
    #url(r'^', include('registration.backends.default.urls')),
    url(r'^', include('registration.backends.simple.urls')), ## temporary no email activation

    (r'^lookups/', include('ajax_select.urls')),

    url(r'^', include('webapp.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


    #url(r'^$', registration/registration_form),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #url(r'^admin/', include(admin.site.urls)),
#)

handler404 = 'webapp.views.custom_404'
handler500 = 'webapp.views.custom_500'

webapp/urls.py
from django.conf.urls.defaults import patterns, url

from webapp.views import *

urlpatterns = patterns('webapp.views', 
    # temporary url for YC
    url(r'^yc/$', 'yc_no_login'),
    url(r'^yc/(?P<extra>[-\w]+)', 'yc_no_login'),


    #### end ####
    url(r'^$', index, 
                #{'backend' : 'registration.backends.default.DefaultBackend'},
                #### modified for simple activation ####
                {'backend' : 'registration.backends.simple.SimpleBackend'},
                name='webapp_index'),
    url(r'^uncat_library', index_uncat, name='webapp_index_uncat'),
    url(r'^invited/(?P<invitation_key>\w+)/$', 
                #index, {'backend' : 'registration.backends.default.DefaultBackend'},
                #### modified for simple activation ####
                index, {'backend' : 'registration.backends.simple.SimpleBackend'},
                name='invitation_invited'), # change if works
    url(r'^validate/email_duplicates/$', 
                'validate_email_duplicate'),
    url(r'^create/$', create, name='create'),
    url(r'^welcome/hello-world/experience$', helloworld, name='webapp_helloworld'),
    url(r'^welcome/hello-world/create$', helloworld_create, name='webapp_helloworld_create'),
    #url(r'^welcome/hello-world/personalize$', helloworld_generator, name='webapp_helloworld_generator'),
    #url(r'^welcome/hello-world/invite$', helloworld_invite, name='webapp_helloworld_invite'),

    # hardcoded in webapp.views.macromeme_publish for HttpResponse
    (r'^welcome/hello-world/publish/$', 'macromeme_publish'),
    (r'^welcome/hello-world/library/$', 'library'),
    (r'^welcome/hello-world/ohwhy/$', 'fb_privacy_explanation'), 

    url(r'album/from_album_invite/(?P<album_id>\w+)/$',
                from_album_invite,
                name='webapp_from_album_invite'),

    (r'^create/library/$', 'library'),
    (r'^create/publish/$', 'macromeme_publish'),
    (r'^create/remix/(?P<meme_id>\d+)', 'library'),
    (r'^create/ohwhy/$', 'fb_privacy_explanation'),
    url(r'^add_experience/$', add_experience, name='add_experience'),
    url(r'delete/(?P<delete_meme_id>\w+)/$',
                delete_meme,
                name='webapp_delete'),
    url(r'^recreate_map/(?P<meme_id>\w+)/$',
                recreate_map,
                name='webapp_recreate_map'),
    url(r'^add_meme_to_node/$',
                add_meme_to_node,
                name='webapp_add_meme_to_node'),
    url(r'deletealbum/(?P<delete_album_id>\w+)/$',
                delete_album,
                name='webapp_deletealbum'),
    #(r"^(\d+)/$", "show_experience"),
    url(r"^(\d+)/$", 
            show_experience,
            name='webapp_show_experience'),
    (r'^meme_in_album/$', 'meme_in_album'),
    (r'^(?P<linked_username>[-\w]+)/$', 'linked_username'),
    url(r'^thatsrightmax/privatetracking', privatetracking, name='webapp_privatetracking'),
    url(r'^thatsrightmax/userlist', userlist, name='webapp_userlist'),
)

webapp/models.py
from django.db import models
from django.contrib.auth.models import User

User._meta.get_field('username')._unique = False

from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

# for private tracking
from datetime import datetime
import os
from django.conf import settings

class Experiences(models.Model):
    # user id
    title = models.CharField(max_length=60)
    creator = models.ManyToManyField(User, blank=True)

    # add invited field to for users to be added in when invited.

    album_pic = models.ForeignKey('Meme', blank=True, null=True)

    def __unicode__(self):
        return self.title

class Meme(models.Model):
    image = models.ImageField(upload_to='images/%Y/%m%d')
    source_content = models.ImageField(upload_to='images/%Y/%m%d', null=True)

    creator = models.ForeignKey(User, null=True, blank=True)

    # many-to-many relationship with the experiences
    e = models.ManyToManyField(Experiences, blank=True)
    #created = models.DateTimeField(auto_now_add=True)

    #### RECREATION ####
    # perspectives linked together
    meme_horizontal = models.ManyToManyField('self', blank=True, null=True)

    # plotlines linked together
    meme_vertical = models.ForeignKey('self', blank=True, null=True)

    # for macromeme generator
    type = models.CharField(max_length=60, blank=True)
    #thumb = models.CharField(max_length=60, blank=True)  # path to relative path
    source = models.CharField(max_length=180, blank=True) # path to relative path


    title = models.CharField(max_length=90, blank=True)
    top_caption = models.CharField(max_length=180, blank=True)
    bottom_caption = models.CharField(max_length=180, blank=True)

    def __unicode__(self):
        return self.image.name

#@receiver(post_delete, sender=Meme)
#def post_delete_user(sender, instance, *args, **kwargs):
    #instance.image.delete(save=False)
    #instance.source_content.delete(save=False)

class MemeLibrary(models.Model):
    type = models.CharField(max_length=60, blank=True)
    thumb = models.CharField(max_length=180, blank=True)
    source = models.CharField(max_length=180, blank=True)
    title = models.CharField(max_length=90, blank=True)
    top_caption = models.CharField(max_length=180, blank=True)
    bottom_caption = models.CharField(max_length=180, blank=True)

    def __unicode__(self):
        return 'Title: '+self.title+' Source: '+self.source

class UserProfile(models.Model):  
    user = models.OneToOneField(User)  
    url_username = models.CharField(max_length=60)
    is_first_login = models.BooleanField(default=True)
    school = models.CharField(max_length=60, blank=True)

    def __str__(self):  
          return "%s's profile" % self.user  

def create_user_profile(sender, instance, created, **kwargs):  
    if created:  
        profile, created = UserProfile.objects.get_or_create(user=instance)  

        # add profile information for social auth after registration
        profile.url_username = profile.user.username.replace(' ','-') 
        count_existing = UserProfile.objects.filter(url_username__iexact=profile.url_username).count() # count existing url_username duplicates

        if count_existing !=0:
            profile.url_username = profile.url_username + '-' + str(count_existing)

        # private tracking code
        date = []
        date.append(str(datetime.now()))

        with open(os.path.join(settings.STATIC_ROOT, 'registration_track.txt'), "a") as text_file:
            text_file.write(date[0]+'   '+profile.user.username+' registered with '+profile.user.email+'\n')

        profile.save()

post_save.connect(create_user_profile, sender=User) 

webapp/forms.py
from django import forms
from ajax_select.fields import AutoCompleteSelectMultipleField

class ImageUploadForm(forms.Form):
    image = forms.ImageField()

class AddExperienceForm(forms.Form):
    title = forms.CharField(max_length=60,
                                widget=forms.TextInput(attrs={'placeholder': 'Our Shared Experience'}))

class InvitationKeyForm(forms.Form):
    email = forms.EmailField()

class SearchForm(forms.Form):

    #q = AutoCompleteField(
    #q = AutoCompleteSelectField(
    q = AutoCompleteSelectMultipleField(
            'label',
            required=True,
            help_text="Invite via email or add an existing user",
            label="",
            #attrs={'size': 100}
            )

class TutorialNameForm(forms.Form):
    friend_name = forms.CharField(max_length=70,
                                widget=forms.TextInput(attrs={'placeholder': 'Friend\'s name'}))

endless_pagination/views.py
"""Django Endless Pagination class-based views."""

from django.core.exceptions import ImproperlyConfigured
from django.http import Http404
from django.utils.encoding import smart_str
from django.utils.translation import ugettext as _
from django.views.generic.base import View
from django.views.generic.list import MultipleObjectTemplateResponseMixin

from endless_pagination.settings import PAGE_LABEL


class MultipleObjectMixin(object):

    allow_empty = True
    context_object_name = None
    model = None
    queryset = None

    def get_queryset(self):
        """Get the list of items for this view.

        This must be an interable, and may be a queryset
        (in which qs-specific behavior will be enabled).

        See original in ``django.views.generic.list.MultipleObjectMixin``.
        """
        if self.queryset is not None:
            queryset = self.queryset
            if hasattr(queryset, '_clone'):
                queryset = queryset._clone()
        elif self.model is not None:
            queryset = self.model._default_manager.all()
        else:
            msg = u'{0} must define ``queryset`` or ``model``'
            raise ImproperlyConfigured(msg.format(self.__class__.__name__))
        return queryset

    def get_allow_empty(self):
        """Returns True if the view should display empty lists.

        Return False if a 404 should be raised instead.

        See original in ``django.views.generic.list.MultipleObjectMixin``.
        """
        return self.allow_empty

    def get_context_object_name(self, object_list):
        """Get the name of the item to be used in the context.

        See original in ``django.views.generic.list.MultipleObjectMixin``.
        """
        if self.context_object_name:
            return self.context_object_name
        elif hasattr(object_list, 'model'):
            object_name = object_list.model._meta.object_name.lower()
            return smart_str('{0}_list'.format(object_name))
        else:
            return None

    def get_context_data(self, **kwargs):
        """Get the context for this view.

        Also adds the *page_template* variable in the context.

        If the *page_template* is not given as a kwarg of the *as_view*
        method then it is generated using app label, model name
        (obviously if the list is a queryset), *self.template_name_suffix*
        and *self.page_template_suffix*.

        For instance, if the list is a queryset of *blog.Entry*,
        the template will be ``blog/entry_list_page.html``.
        """
        queryset = kwargs.pop('object_list')
        page_template = kwargs.pop('page_template')

        context_object_name = self.get_context_object_name(queryset)
        context = {'object_list': queryset}
        context.update(kwargs)
        if context_object_name is not None:
            context[context_object_name] = queryset

        if page_template is None:
            if hasattr(queryset, 'model'):
                page_template = self.get_page_template(**kwargs)
            else:
                raise ImproperlyConfigured(
                    u'AjaxListView requires a page_template')
        context['page_template'] = self.page_template = page_template

        return context


class BaseListView(MultipleObjectMixin, View):

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        allow_empty = self.get_allow_empty()
        if not allow_empty and len(self.object_list) == 0:
            msg = _(u'Empty list and ``%(class_name)s.allow_empty`` is False.')
            raise Http404(msg % {'class_name': self.__class__.__name__})
        context = self.get_context_data(
            object_list=self.object_list, page_template=self.page_template)
        return self.render_to_response(context)


class AjaxMultipleObjectTemplateResponseMixin(
        MultipleObjectTemplateResponseMixin):

    key = PAGE_LABEL
    page_template = None
    page_template_suffix = '_page'
    template_name_suffix = '_list'

    def get_page_template(self, **kwargs):
        """Return the template name used for this request.

        Only called if *page_template* is not given as a kwarg of
        *self.as_view*.
        """
        opts = self.object_list.model._meta
        return '{0}/{1}{2}{3}.html'.format(
            opts.app_label,
            opts.object_name.lower(),
            self.template_name_suffix,
            self.page_template_suffix,
        )

    def get_template_names(self):
        """Switch the templates for Ajax requests."""
        request = self.request
        querystring_key = request.REQUEST.get('querystring_key', PAGE_LABEL)
        if request.is_ajax() and querystring_key == self.key:
            return [self.page_template]
        return super(
            AjaxMultipleObjectTemplateResponseMixin, self).get_template_names()


class AjaxListView(AjaxMultipleObjectTemplateResponseMixin, BaseListView):
    """Allows Ajax pagination of a list of objects.

    You can use this class-based view in place of *ListView* in order to
    recreate the behaviour of the *page_template* decorator.

    For instance, assume you have this code (taken from Django docs)::

        from django.conf.urls.defaults import *
        from django.views.generic import ListView

        from books.models import Publisher

        urlpatterns = patterns('',
            (r'^publishers/$', ListView.as_view(model=Publisher)),
        )

    You want to Ajax paginate publishers, so, as seen, you need to switch
    the template if the request is Ajax and put the page template
    into the context as a variable named *page_template*.

    This is straightforward, you only need to replace the view class, e.g.::

        from django.conf.urls.defaults import *

        from books.models import Publisher

        from endless_pagination.views import AjaxListView

        urlpatterns = patterns('',
            (r'^publishers/$', AjaxListView.as_view(model=Publisher)),
        )

    NOTE: Django >= 1.3 is required to use this view.
    """

webapp/templates/base.html
{% comment %}
  Base.html template is the base design we build on top of. 
  Only add code here to show on entire site 
{% endcomment %}

<!DOCTYPE html>
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/mainpg.css"/>
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap.min.css"/>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

  <head>
    <title>{% block title %}Memeja{% endblock %}</title>
    {{ analytics_code }} 

    {% block landingpageloaded %}
    {% endblock %}
  </head>

  {% block header %}
    <div id="header_container">

      {% block logo %}
        <div id="intro_logo">
          <a href="/" title="Memeja!"><img src="{{ STATIC_URL }}images/intro_logo.gif" style="width:130px;height:40px;"/></a>
        </div>
      {% endblock %}
        {% if user.is_authenticated %}
        {# permanent header at top in base.html #}
          <div ="header_menu_container">
            <ul id="header_menu">
              <li><a href="/logout/">Logout</a></li>
              <li><a href="/">Profile</a></li>
              <li><a href="/create" style="color:#33CCFF">Create</a></li>
            </ul>
          </div>
        {% else %}
        <a href="/login/">Log in</a> 
        {% endif %}
    </div>

  {% block feeduncatstrip %}
	<div id="subheader_container">
<!-- Temp Solution  -->
   <div id="left_balance">
    </div>

    <span id="subheader_menu">
      {% if is_uncat %}
        {# User is on uncat page #}
        <span id="school_subheader_link">
          {% if user_school %}
            <a href="{% url webapp_index %}">{{ user_school }} Feed</a>
          {% endif %}
        </span>
        <span id="uncat_text">
          Uncategorized 
        </span>
        <span class="uncat_header_text_addition">
          (Drag into an album)
        </span>
        
      {% elif is_album %}
        {# User is on uncat page #}
        <span id="school_subheader_link">
          {% if user_school %}
			<a href="{% url webapp_index %}">{{ user_school }} Feed</a>
			
          {% endif %}
        </span>
        <span> | </span>
        <span id="uncategorized_subheader_link">
          <a href="{% url webapp_index_uncat %}">Uncategorized</a>
        </span>
      {% else %}
          {# User is on School feed page #}
         {% if user_school %}
		   <span id="school_text"> {{ user_school }} Feed
		    <span class="uncat_header_text_addition">
				(Drag into an album)
			</span>
		   
		   </span>
         {% endif %}
        <span id="uncategorized_subheader_link">
          <a href="{% url webapp_index_uncat %}">Uncategorized</a>
        </span>
      {% endif %}
    </span>
     
    {% block base_upload %}
     <div id="upload_button_container" >
          <form action="{% url create %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ imageform.non_field_errors }}
            {{ imageform.docfile.label_tag }} {{ imageform.docfile.help_text }}
            {{ imageform.image.errors }}
            {{ imageform.image }}
                <input type="submit" value="Upload" /></p>
          </form>
        </div>
    {% endblock %}
	  
    <div style ="clear:both;"></div>
  </div>
  {% endblock %}

  {% endblock %}

   <body>
       {% block content %}
       {% endblock %}
    
       {% block content-related %}
       {% endblock %}
   </body>

{# Olark Code #}
<script data-cfasync="false" type='text/javascript'>/*{literal}<![CDATA[*/
window.olark||(function(c){var f=window,d=document,l=f.location.protocol=="https:"?"https:":"http:",z=c.name,r="load";var nt=function(){f[z]=function(){(a.s=a.s||[]).push(arguments)};var a=f[z]._={},q=c.methods.length;while(q--){(function(n){f[z][n]=function(){f[z]("call",n,arguments)}})(c.methods[q])}a.l=c.loader;a.i=nt;a.p={0:+new Date};a.P=function(u){a.p[u]=new Date-a.p[0]};function s(){a.P(r);f[z](r)}f.addEventListener?f.addEventListener(r,s,false):f.attachEvent("on"+r,s);var ld=function(){function p(hd){hd="head";return["<",hd,"></",hd,"><",i,' onl' + 'oad="var d=',g,";d.getElementsByTagName('head')[0].",j,"(d.",h,"('script')).",k,"='",l,"//",a.l,"'",'"',"></",i,">"].join("")}var i="body",m=d[i];if(!m){return setTimeout(ld,100)}a.P(1);var j="appendChild",h="createElement",k="src",n=d[h]("div"),v=n[j](d[h](z)),b=d[h]("iframe"),g="document",e="domain",o;n.style.display="none";m.insertBefore(n,m.firstChild).id=z;b.frameBorder="0";b.id=z+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){b.src="javascript:false"}b.allowTransparency="true";v[j](b);try{b.contentWindow[g].open()}catch(w){c[e]=d[e];o="javascript:var d="+g+".open();d.domain='"+d.domain+"';";b[k]=o+"void(0);"}try{var t=b.contentWindow[g];t.write(p());t.close()}catch(x){b[k]=o+'d.write("'+p().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};ld()};nt()})({loader: "static.olark.com/jsclient/loader0.js",name:"olark",methods:["configure","extend","declare","identify"]});
/* custom configuration goes here (www.olark.com/documentation) */
olark.identify('1443-267-10-6798');/*]]>{/literal}*/</script><noscript><a href="https://www.olark.com/site/1443-267-10-6798/contact" title="Contact us" target="_blank">Questions? Feedback?</a> powered by <a href="http://www.olark.com?welcome" title="Olark live chat software">Olark live chat software</a></noscript>

{# end #}

webapp/templates/base_backup.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/mainpg.css"/>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<title>{% block title %}Memeja{% endblock %}</title>
		<div id="cloud_container">
				<div id="cloud_1" class="large_cloud"></div>
				<div id="cloud_2" class="large_cloud"></div>
				<div id="cloud_3" class="large_cloud"></div>
				<div id="cloud_4" class="large_cloud"></div>
				<div id="cloud_5" class="cloud"></div>
				<div id="cloud_6" class="cloud"></div>
				<div id="cloud_7" class="cloud"></div>
				<div id="cloud_8" class="cloud"></div>
				<div id="cloud_9" class="cloud"></div>
				<div id="cloud_11" class="cloud"></div>
				<div id="cloud_12" class="cloud"></div>
				<div id="cloud_13" class="cloud"></div>
				<div id="cloud_14" class="cloud"></div>
				<div id="cloud_15" class="cloud"></div>
				<div id="cloud_16" class="cloud"></div>
				<div id="cloud_17" class="cloud"></div>	
		</div>

    <div id="sidebar">
      {% block sidebar %}{% endblock %}
    </div>
    
		<div id="video_container">
			<div id="intro_logo">
        <a href="##LBL_SITE_URL##" title="Memeja!"><img src="{{ STATIC_URL }}images/intro_logo.gif"style="width:228px;height:70px;"/></a>
			</div>

   {% block content %}
      {# Sample Comment Code #}
			<div id="headline">Share Experiences With the People You Care About</div>
			<div id="video">
				<iframe src="http://player.vimeo.com/video/47618336?byline=0&amp;portrait=0" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
			</div>
		</div>
   {% endblock %}

   <div id="main_content">
      {% block main_content %}{% endblock %} 
    </div>

		<div id="cta_button">
			<div id="cta_login"class="fb-login-button" size="large" scope="
		    	email,
		    	publish_stream
		    	,user_education_history
		    	{*,user_birthday*}	{* Uncomment to enable *}
		    	">
	        Connect with Facebook
			</div>
			<div id="cta_message">We will never post without your permission</div>
		</div>
		<div id="bottom_bar">
			<table><tr>
			<td><div id="about"><a href="/about.html">About </a></div></td>
			<td><div id="blog"><a href="http://blog.memeja.com">Blog </a></div></td>
			<td><div id="privacy_policy"><a href="/privacypolicy.html">Privacy  </a></div></td>
			</tr></table>
		</div>

webapp/templates/privatetracking.html
{% extends 'base.html' %}

{% block content %}

{% if readlogfile %}
  <table class="table table-striped table-hover">
    <div style="position: absolute; top:75px; left:0">{{ readlogfile|linebreaks}}</div>
  </table>
{% endif %}

{% if readlogfile %}
  <table class="table table-striped table-hover">
    <div style="position: absolute; top:75px; left:1000px;">{{ readregfile|linebreaks}}</div>
  </table>
{% endif %}

{% endblock %}

webapp/templates/profile.html
{# Logged in User PROFILE PAGE #}
{# Default profile and album page that logged-in user sees #}
{# Authentication handled in views.index #}

{% extends 'base.html' %}

{# displays new/uncategorized memes to profile for categorization#}
{% block content %}


{# anchor for album to stay #}
<div id="album-anchor"></div>
{# do not remove #}

<div id="albums_container_placeholder">
  <div id="albums_container">
    <div id="albums_header_container">
      <div id="albums_header"> 
         Albums
      </div>
      
      <div style ="clear:both;"></div>
    </div>

    
  {# Displays existing experiences #}
  <div id="create_album_container">
      <div id="create_album">
        <div id="input_field_container">
        <form action="{% url add_experience %}" id="create_album_form" method="post">
          <!--<input placeholder="Album Title" size="6">-->
          {% if addexperienceform.title.errors %}
            <p class="errors">Please correct the errors below: {{ addexperienceform.non_field_errors }}</p>
          {% endif %}
          </div>
          {% csrf_token %}
          {{ addexperienceform.title }}
         <div id="profile_button">
         <input type="submit" value="Create Album" />
         </div>
        
        </div>
      </form>
    </div>
   
	<span id="albums_display_container">

{#### TEMP ####}
    {# TEMPORARY SOLUTION #}
    {% if berkeley %}
		  <div id ="albums_display">
        <span id="hide_text_container">
          <span id="albums_info">
            <a href="/" class="experiences_list" id="{{ berkeley.pk }}" style="font-size:20px;"> {{ berkeley.title }} Feed</a>
          </span>
        </span>
        <a href="/">
            <img src="http://rlv.zcache.com/university_of_california_berkeley_bear_gold_postcard-p239609698918142121b2ork_216.jpg" class="experiences_list" id="{{ berkeley.pk }}" style="height:125px;width:125px;"/>
        </a>
		  </div>
    {% endif %}

    {# TEMPORARY SOLUTION #}
    {% if dartmouth %}
		  <div id ="albums_display">
        <span id="hide_text_container">
          <span id="albums_info">
            <a href="/" class="experiences_list" id="{{
              dartmouth.pk }}" style="font-size:20px;"> {{ dartmouth.title }} Feed</a>
          </span>
        </span>
        <a href="/">
            <img src="http://www.dartmouth.org/classes/63/images/dart.logo.gif" class="experiences_list" id="{{ dartmouth.pk }}" style="height:125px;width:125px;"/>
        </a>
		  </div>
    {% endif %}
{##### end ###}



  {% if experiences %}
    {% for experiences in experiences %}
		  <div id ="albums_display">
        <div id="delete_album_container">
            <a href="{% url webapp.views.delete_album experiences.pk %}"> <i class="icon-remove"></i></a>
        </div>
        <span id="hide_text_container">
          <span id="albums_info">
          <a href="{% url webapp.views.show_experience experiences.pk %}" class="experiences_list" id="{{ experiences.pk }}" style="font-size:20px;"> {{ experiences.title }} </a>
           <!-- ({{ experiences.meme_set.count }} memes)-->
            <div>
            <a> with </a> 
            <class id="coowner">
              {% for creator in experiences.creator.all %}
                {% if not forloop.first %},{% endif %}<a href="/{{ creator.get_profile.url_username }}/">{{ creator.username }}</a> 
              {% endfor %}
            </class>
            </div>
          </span>
        </span>
        <a href="{% url webapp.views.show_experience experiences.pk %}">
          {% if experiences.album_pic %}
          <span id="hide_album_image">
            <img src="{{ MEDIA_URL }}/{{ experiences.album_pic.image }}" class="experiences_list" id="{{ experiences.pk }}" style="height:125px;width:125px;"/>
            {% else %}
            <img src="{{ STATIC_URL }}/images/memeja_logo.png" class="experiences_list" id="{{ experiences.pk }}" style="height:125px;width:125px;"/>
            {% endif %}
          </span>
        </a>
		  </div>
	  </span>
    {% endfor %}
  {% else %}
    </span>
    No experience albums
  {% endif %}
  </div>
	<div style ="clear:both;"></div>
  </div>


 <div id="uncat_container">
  {# Insert flash message when inviting friend #}
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.extra_tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}

  {% if memes and is_uncat %}
        <div id="uncategorized">
          {% for memes in memes %}
            <div class="uncatmemes">
              <a class="fancybox" href="{{ MEDIA_URL }}/{{ memes.image }}">
                <img src="{{ MEDIA_URL }}/{{ memes.image }}" id="{{ memes.pk }}"/>
              </a>
              {% if is_uncat %}
                <span id="delete_uncat_meme"><a href="{% url webapp.views.delete_meme memes.pk %}">Delete</a></span>
              {% endif %}
              {% if memes.top_caption %}
                <div><a href="/create/?meme={{ memes.pk }}">Remix</a></div>
              {% endif %}
            </div>
          {% endfor %}
        </div>
  {% else %}
    <div id="school_feed_memes">
	<div id="perspective_placeholder"></div>
      {% include page_template %}
      {% block js %}
        {{ block.super }}
        <script src="http://code.jquery.com/jquery-latest.js"></script>
        <script src="{{ STATIC_URL }}endless_pagination/endless-pagination.js"></script>
        <script>$.endlessPaginate({paginateOnScroll: true});</script>
      {% endblock %}
    </div>
  {% endif %}
</div>
  {{ standard_js }}
  <script>
  $(document).ready(function($) {
      function sticky_relocate() {
          var window_top = $(window).scrollTop();

          if ($('#album-anchor').length) {
              var offset = $('#album-anchor').offset();
              var div_top = offset.top;
              if (window_top > div_top) {
                  $('#albums_container').addClass('stick');
              } else {
                  $('#albums_container').removeClass('stick');
              }
          }
      }

      $(window).scroll(sticky_relocate);
      sticky_relocate();
  });
  </script>
{% endblock %}